active_domains:
    - 'ibexa_universal_discovery_widget'
    - 'alloy_editor'
    - 'ibexa_fieldtypes_edit'
    - 'ibexa_notifications'
    - 'ibexa_search'
    - 'ibexa_content'
    - 'ibexa_multi_file_upload'
    - 'ibexa_sub_items'
    - 'ibexa_content_tree'
    - 'ibexa_trash_ui'
    - 'ibexa_user_invitationt'
    - 'ibexa_content_type'
    - 'messages'
