active_domains:
    - 'universal_discovery_widget'
    - 'alloy_editor'
    - 'fieldtypes_edit'
    - 'notifications'
    - 'search'
    - 'content'
    - 'multi_file_upload'
    - 'sub_items'
    - 'ibexa_content_tree'
    - 'trash_ui'
    - 'user_invitation'
    - 'ibexa_content_type'
    - 'messages'
